---
resources:
  - name: source-code
    type: git
    source:
      uri: https://miriam.streit:<token>@git.ffhs.ch/miriam.streit/fs24-sema.git
      branch: main
      git_config:
        - name: safe.directory
          value: "*"
  - name: maven-image
    type: registry-image
    source:
      repository: maven
      tag: 3.9
jobs:
  - name: job
    plan:
      - get: source-code
      - get: maven-image
      - task: lint-task
        image: maven-image
        config:
          platform: linux
          inputs:
            - name: source-code
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd source-code/projects/spring-boot
                unset MAVEN_CONFIG
                ./mvnw checkstyle:check

      - task: test-task
        image: maven-image
        config:
          inputs:
            - name: source-code
          platform: linux
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd source-code/projects/spring-boot
                unset MAVEN_CONFIG
                ./mvnw test

      - task: build-task
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
          - name: source-code
          outputs:
          - name: image
          params:
            CONTEXT: source-code/projects/spring-boot
            UNPACK_ROOTFS: true
          run:
            path: build
